---
- hosts: "{{ hosts | default('servers') }}"
  sudo: true
  roles:
    - installer-snapshot
    - upgrade-server
    - installer-snapshot
    - dist-upgrade-to-testing
    - installer-snapshot
    - reboot
