---
- hosts: "{{ hosts | default('servers') }}"
  sudo: true
  tasks:
    # These are some hacks for the demo because of bootable image 
    # problems.
    - name: Need to update package information
      command: apt-get update
    - name:Fix UUID if missing after build
      command: systemctl reload-or-restart reuuid.service
    - name: Restart the journal for systemd
      command: systemctl reload-or-restart systemd-journald.service

- hosts: "{{ hosts | default('servers') }}"
  sudo: true
  roles:
    - installer-snapshot
    - git
    - golang-go
    - docker.io
    - etcd
    - fleet
    - installer-snapshot
