- name: get nova facts
  nova_facts:
    login_username: "{{ nova_username }}"
    login_password: "{{ nova_password }}"
    login_tenant_name: "{{ nova_tenant_name }}"
    auth_url: "{{ nova_auth_url | default('https://region-b.geo-1.identity.hpcloudsvc.com:35357/v2.0/') }}"
    region_name: "{{ nova_region_name | default('region-b.geo-1') }}"
    key_name: "{{ nova_key_name | default('yourkey') }}"
    wait_for: 200
    security_groups: default

- name: make sure inventory directory exists 
  file: path="{{ nova_inventory_dir }}" state=directory 

- name: nova inventory template (make sure to set inventory dir)
  local_action: template src=inventory.j2 dest="{{ nova_inventory_dir | default('~/inventory') }}/inventory_{{ nova_username }}"

- name: ssh_config file for dynamic hosts
  local_action: template src=ssh_config_dynamic.j2 dest="~/ssh_config_dynamic_{{ nova_username }}"
