---
- name: reboot the server
  command: shutdown -r now "Ansible updates triggered"
  async: 0
  poll: 0
  ignore_errors: true
  tags:
    - reboot

- name: waiting for server to come back
  sudo: false
  local_action: >
    wait_for:
      host: {{ inventory_hostname }}
      timeout: 300
      delay: 0
      port: 22
      state: started
  tags:
    - reboot
