---
- name: ensure tools for fstypes are the latest version
  apt: pkg={{ item }} state=latest
  with_items:
    - btrfs-tools
    - aufs-tools

#- name: unmount /mnt
#  mount: name=/mnt src="{{ docker.mnt_dev |  default('/dev/vdb') }}" fstype="{{ docker.mnt_fstype | default('ext3') }}" state=absent

#- name: format "{{ docker.mnt_dev |  default('/dev/vdb') }}" 
#  command: mkfs."{{ docker.mnt_fstype | default('ext3') }}" -f "{{ docker.mnt_dev |  default('/dev/vdb') }}" 

#- name: mount "{{ docker.mnt_dev |  default('/dev/vdb') }}" /var/lib/docker
#  mount: name=/var/lib/docker src="{{ docker.mnt_dev |  default('/dev/vdb') }}" fstype="{{ docker.mnt_fstype | default('ext3') }}"  state=mounted

- name: unmount /mnt
  mount: name=/mnt src=/dev/vdb fstype=ext3 state=absent

- name: mount /dev/vdb  /var/lib/docker
  mount: name=/var/lib/docker src=/dev/vdb fstype=ext3  state=mounted


- name: ensure docker.io is the latest version
  apt: pkg={{ item }} state=latest
  with_items:
    - docker.io

- name: Add docker user for socket
  user: name=docker shell=/bin/nologin system=yes

- name: Copy docker required systemd units
  copy: src={{ item }}  dest=/etc/systemd/system/{{ item }}  owner=root group=root mode=0644
  with_items:
    - 50-docker-veth.network
    - 50-docker.network
    - docker.service
    - docker.socket

- name: start the docker.service
  service: name=docker.service enabled=yes state=started

