---
- name: ensure tools for fstypes are the latest version
  apt: pkg={{ item }} state=latest
  with_items:
    - btrfs-tools
    - aufs-tools

- name: unmount "{{ docker_mount | default('/dev/vdb') }}" from /mnt
  mount:
    name: /mnt
    src: "{{ docker_mount | default('/dev/vdb') }}"
    fstype: ext3
    state: absent

- name: mount "{{ docker_mount | default('/dev/vdb') }}" to /var/lib/docker
  mount: 
    name: /var/lib/docker 
    src: "{{ docker_mount | default('/dev/vdb') }}" 
    fstype: "{{ docker_fstype | default('auto') }}"
    state: mounted

- name: ensure docker.io is the latest version
  apt: pkg={{ item }} state=latest
  with_items:
    - docker.io

- name: Add docker user for socket
  user: name=docker shell=/bin/nologin system=yes

- name: Copy docker required systemd units
  copy: src={{ item }}  dest=/etc/systemd/system/{{ item }}  owner=root group=root mode=0644
  with_items:
    - 50-docker-veth.network
    - 50-docker.network
    - docker.service
    - docker.socket

- name: start the docker.service
  service: name=docker.service enabled=yes state=started

- name: docker pull items
  command: docker pull {{ item }}
  with_items:
    - capttofu/elasticsearch
    - capttofu/logstash
    - capttofu/sinatra-with-logstash
    - capttofu/nginx
