---
- name: ensure docker.io is the latest version
  apt: pkg={{ item }} state=latest
  with_items:
    - docker.io
    - btrfs-tools

- name: Copy docker required systemd units
  copy: src=/files/{{ item }}  dest=/etc/systemd/system/{{ item }}  owner=root group=root mode=0644
  with_items:
    - 50-docker-veth.network
    - 50-docker.network
    - docker.service
    - docker.socket
    - format-ephemeral.service
    - var-lib-docker.mount

- name: start the etcd.service
  service: name=docker.service enabled=yes state=started

