---
- name: ensure docker.io is the latest version
  apt: pkg={{ item }} state=latest
  with_items:
    - docker.io
    - btrfs-tools

- name: Add docker user for socket
  user: name=docker shell=/bin/nologin system=yes

- name: Copy docker required systemd units
  copy: src={{ item }}  dest=/etc/systemd/system/{{ item }}  owner=root group=root mode=0644
  with_items:
    - 50-docker-veth.network
    - 50-docker.network
    - docker.service
    - docker.socket
    - format-ephemeral.service
    - var-lib-docker.mount

- name: start the format-ephemeral 
  service: name=format-ephemeral enabled=yes state=started

- name: mount var-lib-docker.mount
  service: name=var-lib-docker.mount enabled=yes state=started

- name: start the docker.service
  service: name=docker enabled=yes state=started

