---
- name: ensure docker.io is the latest version
  apt: pkg={{ item }} state=latest
  with_items:
    - docker.io
    - btrfs-tools
    - aufs-tools

- name: Add docker user for socket
  user: name=docker shell=/bin/nologin system=yes

- name: Copy docker required systemd units
  copy: src={{ item }}  dest=/etc/systemd/system/{{ item }}  owner=root group=root mode=0644
  with_items:
    - 50-docker-veth.network
    - 50-docker.network
    - docker.service
    - docker.socket

- name: unmount /mnt
  mount: name=/mnt src=/dev/vdb state=absent

- name: unmount /mnt
  mount: name=/var/lib/docker src=/dev/vdb opts=noatime fstype=auto state=unmounted

- name: start the docker.service
  service: name=docker enabled=yes state=started

