---
- name: get nova facts
  host: localhost
  nova_facts:
    login_username: "{{ nova_username }}"
    login_password: "{{ nova_password }}"
    login_tenant_name: "{{ nova_tenant_name }}"
    auth_url: "{{ nova_auth_url | default('https://region-b.geo-1.identity.hpcloudsvc.com:35357/v2.0/') }}"
    region_name: "{{ nova_region_name | default('region-b.geo-1') }}"
    key_name: "{{ nova_key_name | default('yourkey') }}"
    wait_for: 200
    security_groups: default

- name: upload /etc/environment
  template: src=environment.j2 dest=/etc/environment mode=0644
