---
# make sure the gitconfig is in correct place!  

- name: render gitconfig 
  template: src=gitconfig.j2 dest="{{ remote_home }}/.gitconfig" owner="{{ remote_user }}" group="{{ remote_user }}" mode=0755  

- name: render same gitconfig in root dir
  template: src=gitconfig.j2 dest="/root/.gitconfig" mode=0755  

- name: "checking for {{ install_snapshot.snapshot_dir }}"
  stat: path="{{ install_snapshot.snapshot_dir }}"
  register: snapshot_dir_state

- name: "make {{ install_snapshot.snapshot_dir }}"
  file: path="{{ install_snapshot.snapshot_dir }}" state=directory owner="{{ remote_user }}" group=root mode=0755
  when: snapshot_dir_state.stat.exists == false

- name: upload snapshot script
  template: src=snapshot.j2 dest="{{ install_snapshot.snapshot_dir }}/snapshot.sh" owner="{{ remote_user }}" mode=0755  

- name: create snaphost history of currently installed packages
  shell: "{{ install_snapshot.snapshot_dir }}/snapshot.sh"
