---
- name: apt-get update 
  apt: update_cache=yes cache_valid_time=3600  
  tags:
    - update_cache

- name: apt-get upgrade 
  apt: upgrade=full cache_valid_time=3600 update_cache=yes
  tags:
    - repo
    - upgrade_full

# So during all this trial and error testing I want to make sure
# not to leave around a repo by mistake...
- name: remove deb wheezy repos
  apt_repository: repo={{ item }} state=absent update_cache=no
  with_items:
    - "'deb http://http.debian.net/debian jessie main'" 
    - "'deb http://http.debian.net/debian jessie-updates main'" 
    - "'deb http://security.debian.org jessie/updates main'"
    - "'deb http://http.debian.net/debian wheezy main'"
    - "'deb http://http.debian.net/debian wheezy-updates main'"
    - "'deb http://http.debian.net/debian wheezy-backports main'"
    - "'deb http://security.debian.org/ wheezy/updates'"
    - "'deb-src http://security.debian.org/ wheezy/updates'"
    - "'deb-src http://http.debian.net/debian wheezy main'"
    - "'deb-src http://http.debian.net/debian wheezy-updates main'"
    - "'deb-src http://http.debian.net/debian wheezy-backports main'"
    - "'deb http://http.debian.net/debian testing main'" 
    - "'deb http://http.debian.net/debian testing-updates main'" 
    - "'deb http://http.debian.net/debian unstable main'" 
    - "'deb http://security.debian.org testing/updates main'"
    - "'deb-src http://security.debian.org testing/updates main'"
    - "'deb-src http://http.debian.net/debian testing main'" 
    - "'deb-src http://http.debian.net/debian testing-updates main'" 
    - "'deb-src http://http.debian.net/debian jessie main'" 
    - "'deb-src http://http.debian.net/debian jessie-updates main'" 
    - "'deb-src http://security.debian.org jessie/updates main'"
  tags:
    - repo

# Lets add the testing repo now.
- name: add deb testing repo
  apt_repository: repo={{ item }} state=present update_cache=no
  with_items:
    - "'deb http://http.debian.net/debian testing main'" 
    - "'deb http://http.debian.net/debian testing-updates main'" 
    - "'deb http://security.debian.org testing/updates main'"
  tags:
    - repo

- name: add src deb testing repo
  apt_repository: repo={{ item }} state=present update_cache=no
  with_items:
    - "'deb-src http://http.debian.net/debian testing main'" 
    - "'deb-src http://http.debian.net/debian testing-updates main'" 
    - "'deb-src http://security.debian.org testing/updates main'"
  tags:
    - repo

- name: setting up dpkg priority /etc/apt/preferences.d/testing
  template: src=testing.j2 dest=/etc/apt/preferences.d/testing mode=0644
  tags:
    - repo

# Now that the apt sources have been modifed try a dist-upgrade
- name: dist-upgrade a server (may fail)
  apt: update_cache=yes upgrade=dist dpkg_options='force-confold,force-confdef'
  register: apt_result 
  ignore_errors: True
  tags:
    - repo

# Try to do the dist-upgrade again
- name: dist-upgrade a server one more time
  apt: update_cache=no upgrade=dist dpkg_options='force-confold,force-confdef'
  when: "'FAILED' in apt_result.stderr"
  tags:
    - repo

- name: Fix the kernel to boot to the right one
  replace: dest=/boot/extlinux/linux.cfg regexp='3\.2\.0\-4' replace='3.16-3' owner=root group=root mode=644
  tags:
    - repo

- name:  Re-run extlinux --update /boot/extlinux
  command: /usr/bin/extlinux --update /boot/extlinux

