---
- name: apt-get update 
  apt: update_cache=yes cache_valid_time=3600  
  tags:
    - update_cache

- name: apt-get upgrade 
  apt: upgrade=full cache_valid_time=3600 update_cache=yes
  tags:
    - repo
    - upgrade_full

- name: remove deb wheezy repos
  apt_repository: repo={{ item }} state=absent update_cache=no
  with_items:
    - "'deb http://http.debian.net/debian wheezy main'"
    - "'deb http://http.debian.net/debian wheezy-updates main'"
    - "'deb http://http.debian.net/debian wheezy-backports main'"
    - "'deb-src http://http.debian.net/debian wheezy main'"
    - "'deb-src http://http.debian.net/debian wheezy-updates main'"
    - "'deb-src http://http.debian.net/debian wheezy-backports main'"
  tags:
    - repo

# Lets add the testing repo now.
- name: add deb testing repo
  apt_repository: repo={{ item }} state=present update_cache=no
  with_items:
    - "'deb http://http.debian.net/debian testing main'" 
    - "'deb http://http.debian.net/debian testing-updates main'" 
    - "'deb http://security.debian.org testing/updates main'"
    - "'deb http://http.debian.net/debian unstable main'" 
    - "'deb http://http.debian.net/debian unstable-updates main'" 
    - "'deb http://security.debian.org unstable/updates main'"
    - "'deb-src http://security.debian.org testing/updates main'"
    - "'deb-src http://http.debian.net/debian testing main'" 
    - "'deb-src http://http.debian.net/debian testing-updates main'" 
  tags:
    - repo

- name: setting up dpkg priority /etc/apt/preferences.d/testing
  template: src=testing.j2 dest=/etc/apt/preferences.d/testing mode=0644
  tags:
    - repo

# Try to do the upgrade again
- name: dist-upgrade a server
  apt: update_cache=yes upgrade=dist dpkg_options='force-confold,force-confdef'
  tags:
    - repo
