---
- name: "Debug hostname"
  debug: msg="inventory_hostname={{ inventory_hostname }}, hostvars[inventory_hostname]['inventory_hostname']={{ hostvars[inventory_hostname]['inventory_hostname'] }}, ansible_hostname={{ ansible_hostname }}, new_hostname={{ new_hostname }}"
  ignore_errors: yes

# roles/hosts/tasks/main.yml
---
- name: change /etc/hosts
  template: src=hosts.j2 dest=/etc/hosts

- name: change /etc/hostname
  template: src= hostname.j2 dest=/etc/hosts

- name: set hostname
  command: hostname "{{ inventory_hostname }}"

