---
- hosts: servers
  sudo: true

  vars:
    fleet:
      repo: https://github.com/coreos/fleet.git
      clone: /srv/fleet-src
      version: v0.8.2

  tasks:
  - name: ensure golang is the latest version
    apt: pkg={{ item }} state=latest
    with_items:
      - git
      - golang-go

  - name: check if fleet {{ fleet.version }} is already at {{ fleet.clone }}/bin/fleet
    stat: path={{ fleet.clone }}/bin/fleetd
    register: fleet_result

  - name: clone fleet {{ fleet.version }}
    git: repo={{ fleet.repo }}
       dest={{ fleet.clone }}
       version={{ fleet.version }}
    register: fleet_cloned_done
    when: fleet_result.stat.exists == false

  - name: build fleet {{ fleet.version }} from {{  fleet.repo }}
    command: chdir={{ fleet.clone }} ./build
    when: fleet_result.stat.exists == false and fleet_cloned_done|success

