---
- hosts: servers
  sudo: true

  vars:
    etcd:
      repo: https://github.com/coreos/etcd.git
      clone: /srv/etcd-src
      version: v0.4.6

    etcdctl:
      repo: https://github.com/coreos/etcdctl.git
      clone: /srv/etcdctl-src
      version: v0.4.5
    

  tasks:
  - name: ensure golang is the latest version
    apt: pkg={{ item }} state=latest
    with_items:
      - git
      - golang-go

  - name: check if ectd {{ etcd.version }} is already at {{ etcd.clone }}/bin/etcd
    stat: path={{ etcd.clone }}/bin/etcd
    register: etcd_result

  - name: clone ectd {{ etcd.version }}
    git: repo={{ etcd.repo }}
       dest={{ etcd.clone }}
       version={{ etcd.version }}
    register: ectd_cloned_done
    when: etcd_result.stat.exists == false

  - name: build etcd {{ etcd.version }} from {{  etcd.repo }}
    command: chdir={{ etcd.clone }} ./build
    when: etcd_result.stat.exists == false and ectd_cloned_done|success

  - name: check if ectdctld {{ etcdctl.version }} is already at {{ etcdctl.clone }}/bin/etcd
    stat: path={{ etcdctl.clone }}/bin/etcd
    register: etcdctl_result

  - name: clone ectdctl {{ etcdctl.version }}
    git: repo={{ etcdctl.repo }}
       dest={{ etcdctl.clone }}
       version={{ etcdctl.version }}
    register: ectdctl_cloned_done
    when: etcdctl_result.stat.exists == false

  - name: build etcdctl {{ etcdctl.version }} from {{  etcdctl.repo }}
    command: chdir={{ etcdctl.clone }} ./build
    when: etcdctl_result.stat.exists == false and ectdctl_cloned_done|success
